#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'rvm', :git => 'https://github.com/fnichol/chef-rvm'
#
cookbook 'osx-apps', :path => 'site-cookbooks/osx-apps'

cookbook 'homebrew'
cookbook 'dmg'
cookbook 'zip_app'
cookbook 'mac_os_x'
cookbook 'xquartz'

